services:
  - type: web
    name: laravel-app
    runtime: docker
    plan: free
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:L7+dH4IAlx3cnLYpSK14XMkQBAsgst91oTORUKhC8o4=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://votre-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: shuttle.proxy.rlwy.net
      - key: DB_PORT
        value: 31257
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: uLABjOgnwHKoJMQeEFNeoARJLepRsbeT
      - key: MYSQL_ATTR_SSL_CA
        value: ""
      - key: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
        value: false
      - key: DB_SSL_MODE
        value: REQUIRED
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync